[package]
name = "sgthr7-lib-num-traits-bounded"
version = "0.1.0"
edition = "2018"
authors = ["SGThr7 <sgthr7@gmail.com>"]
license = "MIT"

[lib]
name = "num_traits_bounded"

[dependencies]
sgthr7-lib-num-traits-macro-impl-id = { path = "../num-traits-macro-impl-id" }
