[package]
name = "sgthr7-lib-rational"
version = "0.1.0"
edition = "2018"
authors = ["SGThr7 <sgthr7@gmail.com>"]
license = "MIT"

[lib]
name = "rational"

[dependencies]
sgthr7-lib-gcd-lcm = { path = "../gcd-lcm" }
sgthr7-lib-macro-forward-ref-binop = { path = "../macro-forward-ref-binop" }
