[package]
name = "sgthr7-lib-chmax"
version = "0.1.0"
edition = "2018"
authors = ["SGThr7 <sgthr7@gmail.com>"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
