[package]
name = "sgthr7-lib-fenwick-tree"
version = "0.1.0"
edition = "2018"
authors = ["SGThr7 <sgthr7@gmail.com>"]
license = "MIT"

[lib]
name = "fenwick_tree"

[dependencies]
sgthr7-lib-monoid = { path = "../monoid" }
sgthr7-lib-bisect = { path = "../bisect" }
